# Generated by Django 2.2.4 on 2019-09-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuretenure',
            name='esusu_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='future_tenure', to='tenures.EsusuGroup'),
        ),
    ]
